# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# Development
web.socket.url: ws://localhost:8080/stomp

# Production
#web.socket.url: ws://lingo.charego.com/stomp
